version: "3"
services:
  nginx:
    image: jwilder/nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./shared/certs:/etc/nginx/certs
      - ./shared/vhost.d:/etc/nginx/vhost.d
      - ./shared/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    container_name: webproxy_nginx
  companion: 
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    environment:
      - DEFAULT_EMAIL=james@blamks.by
      - NGINX_PROXY_CONTAINER=webproxy_nginx
    volumes:
      - ./shared/certs:/etc/nginx/certs
      - ./shared/vhost.d:/etc/nginx/vhost.d
      - ./shared/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: webproxy_letsencrypt
networks:
  default:
    external:
      name: webproxy
