version: "3"
services:
  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PLEX_CLAIM=claim-8zi9hsPDoKzDh8DXEfnP
      - ADVERTISE_IP=http://10.10.0.2:32400/
      - TZ=Europe/London
      - PLEX_UID=1000
      - PLEX_GID=1000
      - VIRTUAL_HOST=plex.blanks.by
      - VIRTUAL_PORT=32400
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=plex.blanks.by
    volumes:
      - $PWD/storage/database:/config
      - $PWD/storage/transcode:/transcode
      - /volume/video/movie:/data/movies
      - /volume/video/tv:/data/tvshows
      - /volume/user/james/Pictures/iPhone/:/data/pictures/James
      - /volume/user/anna/Pictures/iPhone/:/data/pictures/Anna
    hostname: srv
    container_name: plex
networks:
  default:
    external:
      name: webproxy
