version: "3"
services:
  deluge:
    image: binhex/arch-delugevpn
    restart: unless-stopped
    ports:
      - 8112:8112
      - 8118:8118
      - 58846:58846
      - 58946:58946
    environment:
      - VPN_ENABLED=yes
      - VPN_USER=
      - VPN_PASS=
      - VPN_PROV=
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=10.40.0.0/24
      - NAME_SERVERS=209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1 
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=info
      - DEBUG=false
      - PUID=0
      - PGID=0
      - UMASK=022
    volumes:
      - ./conf:/config
      - ./storage/data:/data
      - /volume/torrent/watch:/torrent/watch
      - /volume/torrent/incomplete:/torrent/incomplete
      - /volume/torrent/complete:/torrent/complete
      - /etc/localtime:/etc/localtime:ro
    cap_add: 
      - NET_ADMIN
    container_name: deluge
