version: "3"
services:
  sonarr:
    image: linuxserver/sonarr:preview
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=0
      - PGID=0
      - UMASK_SET=022
      - TZ=Europe/London
    volumes:
      - $PWD/conf:/config
      - /volume/torrent/complete:/downloads
      - /volume/video/tv:/tv
    deploy:
      resources:
         limits:
            cpus: "0.25"
    container_name: sonarr
