version: "3"
services:
  motion:
    build: ./motion
    restart: unless-stopped
    ports:
      - 7999:7999
      - 8061:8061
    environment:
      - TZ=Europe/London
    volumes:
      - $PWD/motion/conf:/usr/local/etc/motion
      - $PWD/motion/storage:/var/lib/motion
    depends_on:
      - database
    labels:
      - com.centurylinklabs.watchtower.enable=false
    container_name: protect_motion
  database:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      - TZ=Europe/London
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_HOST=0.0.0.0
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
    volumes:
      - $PWD/database/conf:/docker-entrypoint-initdb.d
      - $PWD/database/storage:/var/lib/mysql
    container_name: protect_database
  vision:
    build: ./vision
    restart: unless-stopped
    ports:
      - 8060:8060
    environment:
      - TZ=Europe/London
    volumes:
      - $PWD/vision/storage:/usr/src/
      - $PWD/motion/storage:/usr/src/root/lib
      - /usr/src/node_modules
    labels:
      - com.centurylinklabs.watchtower.enable=false
    container_name: protect_vision
  cron:
    build: ./cron
    restart: unless-stopped
    volumes:
      - $PWD/cron/conf/task:/var/www
      - $PWD/motion/storage:/var/lib
    labels:
      - com.centurylinklabs.watchtower.enable=false
    container_name: protect_cron
    

