version: "3"
services:
  motion:
    build: ./motion
    restart: unless-stopped
    ports:
      - 7999:7999
      - 8061:8061
    environment:
      - TZ=Europe/London
    volumes:
      - ./motion/conf:/usr/local/etc/motion
      - ./motion/storage:/var/lib/motion
    depends_on:
      - database
    labels:
      - com.centurylinklabs.watchtower.enable=false
    container_name: protect_motion
  database:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      - TZ=Europe/London
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_HOST=0.0.0.0
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
    volumes:
      - ./database/conf:/docker-entrypoint-initdb.d
      - ./database/storage:/var/lib/mysql
    container_name: protect_database
  vision:
    build: ./vision
    restart: unless-stopped
    ports:
      - 8060:8060
    environment:
      - TZ=Europe/London
    volumes:
      - ./vision/conf/config.js:/usr/src/config.js
      - ./motion/storage/:/usr/src/root/lib
    labels:
      - com.centurylinklabs.watchtower.enable=false
    container_name: protect_vision
  cron:
    build: ./cron
    restart: unless-stopped
    volumes:
      - ./cron/conf/storage:/var/www
      - ./motion/storage:/var/lib
    labels:
      - com.centurylinklabs.watchtower.enable=false
    container_name: protect_cron
    

