version: "3"
services:
  radarr:
    image: linuxserver/radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=0
      - PGID=0
      - UMASK_SET=022
      - TZ=Europe/London
    volumes:
      - $PWD/conf:/config
      - /volume/torrent/complete:/downloads
      - /volume/video/movie:/movies
    deploy:
      resources:
         limits:
            cpus: "0.25"
    container_name: radarr
