version: "3"
services:
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - $PWD/mongo/storage/db:/data/db
    container_name: unifi_mongo
  controller:
    image: jacobalberty/unifi
    restart: unless-stopped
    ports:
      - 3478:3478/udp
      - 6789:6789/tcp
      - 8080:8080/tcp
      - 8443:8443/tcp
      - 8880:8880/tcp
      - 8843:8843/tcp
      - 10001:10001/udp
    environment:
      - DB_URI=mongodb://mongo/unifi
      - STATDB_URI=mongodb://mongo/unifi_stat
      - DB_NAME=unifi
      - VIRTUAL_HOST=unifi.blanks.by
      - VIRTUAL_PORT=8443
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=unifi.blanks.by
    volumes:
      - $PWD/controller/storage/data:/unifi/data
      - $PWD/controller/storage/log:/unifi/log
      - $PWD/controller/storage/init.d:/unifi/init.d
    depends_on:
      - mongo
    container_name: unifi_controller
networks:
  default:
    external:
      name: webproxy
