version: "3"
services:
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - $PWD/mongo/storage/db:/data/db
    container_name: unifi_mongo
  controller:
    image: jacobalberty/unifi
    restart: unless-stopped
    ports:
      - 3478:3478
      - 6789:6789
      - 8080:8080
      - 8443:8443
      - 8880:8880
      - 8843:8843
      - 10001:10001
    environment:
      - DB_URI=mongodb://mongo/unifi
      - DB_NAME=unifi
      - STATDB_URI=mongodb://mongo/unifi_stat
      - VIRTUAL_HOST=unifi.blanks.by
      - VIRTUAL_PORT=8443
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=unifi.blanks.by
    volumes:
      - $PWD/controller/network/storage/data:/unifi/data
      - $PWD/controller/network/storage/log:/unifi/log
      - $PWD/controller/network/storage/init.d:/unifi/init.d
    depends_on:
      - mongo
    container_name: unifi_controller
networks:
  default:
    external:
      name: webproxy
